---
# tasks file for ansible_role_sshd
- name: 'include variables for the Debian family'
  include_vars: 'vars_os_debian.yml'
  when: |
    ansible_os_family == 'Debian'

- name: 'include variables for OpenBSD'
  include_vars: 'vars_os_openbsd.yml'
  when:
    ansible_system == 'OpenBSD'

- name: 'configure the /etc/sshd/sshd_config file'
  template:
    src: 'sshd_config.j2'
    dest: '/etc/ssh/sshd_config'
  become: yes
  notify: 'reload_sshd'
